version: '3.8'

services:
  backend:
    build:
      context: ./obix-chatbot-backend
      dockerfile: Dockerfile
    container_name: obix-backend
    volumes:
      - ./obix-chatbot-backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=debt_chatbot.settings
      - CORS_ORIGIN_ALLOW_ALL=True
      - PYTHONUNBUFFERED=1
      - GEMINI_API_KEY=AIzaSyA53Q5ntPOItolX3GBUYLPVztRXzFxXgF8
    restart: unless-stopped
    networks:
      - obix-network

  frontend:
    build:
      context: ./obix-chatbot
      dockerfile: Dockerfile
    container_name: obix-frontend
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - obix-network

networks:
  obix-network:
    driver: bridge 