version: '3'

services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - PORT=8000
      - DATABASE_URL=sqlite:///db.sqlite3
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web 