services:
  - type: web
    name: obix-chatbot-backend
    env: python
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn debt_chatbot.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: '*.onrender.com,localhost,127.0.0.1'
      - key: GEMINI_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: obix-chatbot-db
          property: connectionString

databases:
  - name: obix-chatbot-db
    databaseName: obix_chatbot_db
    user: obix_user
    region: ohio
    plan: free 